sudo: true
dist: precise

language: node_js

node_js:
  - "9"

install:
 - npm install

script:
 - npm test

notifications:
  email:
    recipients:
      - umam@sepulsa.com
    on_success: always
    on_failure: always

branches:
 only:
 - master